FROM clarisys/manylinux2:i686

COPY build_scripts/build_tools.sh build_scripts/build_3rdparty_static.sh ./

RUN /build_tools.sh && rm -r /build_tools.sh

ENV PATH /usr/lib/qt4/bin:/usr/local/cmake-2.8.12/bin:${PATH}
ENV PATH /opt/python/cp27-cp27mu/bin/:${PATH}

ENV PREFIX /usr/local
ENV PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig
ENV ESSENTIA_3RDPARTY_VERSION 95cd9a576f0f1ab526165fbb553d73fbe51ce440
RUN /build_3rdparty_static.sh && rm -r /build_3rdparty_static.sh

CMD ["/bin/bash"]
