FROM quay.io/pypa/manylinux_2_28_x86_64:latest

COPY build_scripts/build_tools.sh build_scripts/build_3rdparty_static.sh build_scripts/build_3rdparty_static_debian.sh build_scripts/install_cuda.sh build_scripts/uninstall_cuda.sh build_scripts/build_zlib.sh build_scripts/build_onnx.sh build_scripts/build_config.sh build_scripts/build_chromaprint.sh build_scripts/build_taglib.sh ./

# The manylinux_2_28 image is intended to build essentia-tensorflow wheels
# To build TensorFlow we additionally need Bazel and NumPy.
ENV WITH_TENSORFLOW=false
ENV PYTHON_BIN_PATH=/opt/python/cp310-cp310/bin/python3

# Install cmake3 dependencies
RUN yum install -y vim openssl-devel 	\
	&& yum clean all 		\
	&& rm -rf /var/cache/yum

RUN /build_tools.sh 			\
	&& rm -r /build_tools.sh 	\
	&& yum clean all 		\
	&& rm -rf /var/cache/yum

ENV PATH=/usr/lib64/qt5/bin:/usr/local/cmake-3.28.6/bin:${PATH}
ENV PATH=/opt/python/cp310-cp310/bin/:${PATH}

ENV PREFIX=/usr/local
ENV PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig
ENV ESSENTIA_3RDPARTY_VERSION=v2.1_beta5-810-gafec9ed7

# The only known alternative to the interactive TensorFlow configuration is
# via environment variables:
# https://github.com/tensorflow/tensorflow/issues/8527#issuecomment-289272898
ENV USE_DEFAULT_PYTHON_LIB_PATH=1

ENV BAZEL_LINKLIBS=-l%:libstdc++.a

ENV TF_NEED_JEMALLOC=1
ENV TF_NEED_GCP=0
ENV TF_NEED_HDFS=0
ENV TF_ENABLE_XLA=0
ENV TF_NEED_OPENCL=0

# TensorFlow CUDA & CuDNN versions intended for TensorFlow 2.5
# For future updates check the GPU compatibility chart:
# https://www.tensorflow.org/install/source#gpu
ENV TF_NEED_CUDA=1
ENV TF_CUDA_VERSION=11.2
ENV TF_CUDNN_VERSION=8.1
ENV CUDA_TOOLKIT_PATH=/usr/local/cuda
ENV CUDNN_INSTALL_PATH=/usr/local/cuda

# The compute capabilities define which GPUs can be used:
# https://developer.nvidia.com/cuda-gpus#compute
# Supporting more versions increases the library size, so
# for the moment it is set to a conservative number that
# covers some of the most popular deep learning GPUs:
# 3.5: Geforce GT XXX
# 5.2: Geforce GTX TITAN X
# 7.5: Geforce RTX 2080 (Ti)
# 8.6: Geforce RTX 30XX
ENV TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,7.5,8.6

RUN /install_cuda.sh && /build_3rdparty_static.sh && /uninstall_cuda.sh \
  && rm -r /install_cuda.sh /build_3rdparty_static.sh /uninstall_cuda.sh

CMD ["/bin/bash"]
